#!/bin/sh
exec 1>&2

RED='\033[0;31m'
NC='\033[0m'
SEARCH_TERM="TODO"

if [[ $(git diff --cached | grep -E "^\+" | grep -v '+++ b/' | cut -c 2-) == *$SEARCH_TERM* ]]
then
	printf "${RED}Error:${NC} Found ${SEARCH_TERM} in attempted commit.\n"
	printf "Please remove all occurrences of ${SEARCH_TERM} before committing.\n"
	exit 1
fi
